version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend_base: |
    RUN export NETBOX_API=$NETBOX_API
    RUN export NETBOX_TOKEN=$NETBOX_TOKEN
