---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

options:
    package_manager_path: /usr/bin/microdnf

images:
  base_image:
    name: "registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest"

additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.12-for-rhel-8-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.12-for-rhel-8-x86_64-rpms.enabled=true"

additional_build_files:
  - src: /root/execution-environments/ansible_execution_environments/ocp-vmw-infra-ee/files/redhat-openshift-4.0.0.tar.gz
    dest: mycollections/
  - src: /root/execution-environments/ansible_execution_environments/ocp-vmw-infra-ee/files/redhat-openshift_virtualization-2.1.0.tar.gz
    dest: mycollections/
  - src: /root/execution-environments/ansible_execution_environments/ocp-vmw-infra-ee/files/ansible-platform-2.5.3.tar.gz
    dest: mycollections/
  - src: /root/execution-environments/ansible_execution_environments/ocp-vmw-infra-ee/files/ansible-controller-4.6.2.tar.gz
    dest: mycollections/
