collections:
  - vmware.vmware_rest
  - kubernetes.core
  - infra.aap_configuration
  - ansible.hub
  - name: mycollections/redhat-openshift_virtualization-2.1.0.tar.gz
    type: file
  - name: mycollections/redhat-openshift-4.0.0.tar.gz
    type: file
  - name: mycollections/ansible-platform-2.5.3.tar.gz
    type: file
  - name: mycollections/ansible-controller-4.6.2.tar.gz
    type: file
